### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by AsaAyers** [bradleyboy/tidy-tabs-atom#1]
This seems to happen when I don't close the initial "untitled" tab and TidyTabs tries to close it.

**Atom Version**: 0.184.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [tidy-tabs](https://github.com/bradleyboy/tidy-tabs-atom) package, v0.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\pane.js:782

TypeError: undefined is not a function
  at Object.module.exports.TidyTabs.isCandidate (C:\Users\Asa\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:61:57)
  at Object.<anonymous> (C:\Users\Asa\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:86:39)
  at Object.module.exports.TidyTabs.getItemsToClose (C:\Users\Asa\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:98:10)
  at Object.module.exports.TidyTabs.tidy (C:\Users\Asa\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:47:5)
  at C:\Users\Asa\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:39:18
  at Emitter.module.exports.Emitter.emit (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:974:20)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\text-editor.js:621:26)
  at Pane.module.exports.Pane.saveItem (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\workspace.js:689:35)
  at atom-workspace.atom.commands.add.core:save (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:243:29)
  at C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Asa\AppData\Local\atom\app-0.184.0\resources\app\src\window-event-handler.js:182:20)

```

### Commands

```
     -0:40.9 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:40.2 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode)
     -0:39.7 vim-mode:delete (atom-text-editor.editor.vim-mode.command-mode)
     -0:39.6 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:39.1 vim-mode:indent (atom-text-editor.editor.vim-mode.command-mode)
  2x -0:37.7 vim-mode:outdent (atom-text-editor.editor.vim-mode.command-mode)
     -0:37.1 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode)
     -0:36.6 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.command-mode)
     -0:35.5 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
     -0:35.4 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:34.7 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode)
     -0:32.0 vim-mode:insert-after-end-of-line (atom-text-editor.editor.vim-mode.command-mode)
     -0:31.8 core:backspace (atom-text-editor.editor.vim-mode.command-mode)
     -0:31.2 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.command-mode)
     -0:31.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode)
     -0:30.7 core:save (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "wrap-lines",
      "js-links"
    ],
    "projectHome": "C:\\Users\\Asa\\Documents\\GitHub"
  },
  "tidy-tabs": {
    "runOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.0
autocomplete-snippets, v1.0.1
code-links, v0.3.5
coffee-compile, v0.11.0
coffee-links, v0.1.0
gist-it, v0.6.5
git-difftool, vundefined
highlight-line, v0.10.1
highlight-selected, v0.9.1
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-eslint, v0.4.1
minimap, v4.5.0
minimap-find-and-replace, vundefined
minimap-git-diff, vundefined
minimap-highlight-selected, vundefined
project-manager, v1.15.5
react, v0.9.10
tidy-tabs, v0.1.0
vim-mode, v0.34.0
vim-surround, v0.4.2

# Dev
No dev packages
```

**Comment by bradleyboy** [comment]
@AsaAyers Thanks for reporting. I'm assuming something Windows specific is going on here, as I can't replicate that on OS X. Just pushed 0.1.1 with an extra check that I think should resolve the issue described in the trace. Let me know if you still have issues.
