### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat 'C:\projects\project-dir\project-dir'

### ISSUE THREAD

**Issue by NuclearCookie** [bradleyboy/tidy-tabs-atom#4]
1. Somehow I have a file open in my project that does not really exist ( the file has the same name as my project.
2. When I saved, tidy tabs tried to close the file, but it does not really exist. I suppose it should fail silently

**Atom Version**: 1.0.6
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [tidy-tabs](https://github.com/bradleyboy/tidy-tabs-atom) package, v0.2.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'C:\projects\jira\ce\ce'

```
At C:\Users\Pieter\AppData\Local\atom\app-1.0.6\resources\app.asar\src\pane.js:801

Error: ENOENT: no such file or directory, stat 'C:\projects\jira\ce\ce'
    at Error (native)
    at fs.statSync (fs.js:846:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
    at Object.module.exports.TidyTabs.isCandidate (C:\Users\Pieter\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:81:17)
    at Object.<anonymous> (C:\Users\Pieter\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:95:20)
    at Object.module.exports.TidyTabs.getItemsToClose (C:\Users\Pieter\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:100:10)
    at Object.module.exports.TidyTabs.tidy (C:\Users\Pieter\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:63:19)
    at C:\Users\Pieter\.atom\packages\tidy-tabs\lib\tidy-tabs.coffee:51:28
    at Emitter.module.exports.Emitter.emit (C:\Users\Pieter\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Pieter\AppData\Local\atom\app-1.0.6\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1025:20)
```

### Commands

```
     -1:26.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:26 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:24.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:24.2.0 merge-conflicts:detect (atom-text-editor.editor)
     -0:36.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -0:36.5.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -0:28.3.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -0:19 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
  2x -0:15.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -0:06.7.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "slack-chat",
      "background-tips",
      "bookmarks"
    ]
  },
  "tidy-tabs": {
    "runOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
atom-image-resize, v0.3.0
autoclose-html, v0.18.0
browser-plus, v0.0.34
compare-files, v0.6.2
file-icons, v1.6.3
language-lua, v0.9.4
language-sln, v0.1.0
merge-conflicts, v1.3.5
minimap, v4.12.2
minimap-selection, v4.3.0
project-manager, v1.15.11
run-in-browser, v0.1.3
Sublime-Style-Column-Selection, v1.3.0
tidy-tabs, v0.2.0

# Dev
No dev packages
```

**Comment by bradleyboy** [comment]
Should be resolved in 0.3.0. Let me know if you still have problems.
