### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/home/agordon/dev/Frontier/Prototype/cli...

### ISSUE THREAD

**Issue by ajgordo** [bradleyboy/tidy-tabs-atom#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Ubuntu 14.10
**Thrown From**: [tidy-tabs](https://github.com/bradleyboy/tidy-tabs-atom) package, v0.2.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/home/agordon/dev/Frontier/Prototype/client-datatable/tests/dummy/translations/en-us.json'

```
At /usr/share/atom/resources/app.asar/src/pane.js:809

Error: ENOENT: no such file or directory, stat '/home/agordon/dev/Frontier/Prototype/client-datatable/tests/dummy/translations/en-us.json'
  at Error (native)
  at fs.statSync (fs.js:854:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
  at Object.module.exports.TidyTabs.isCandidate (/home/agordon/.atom/packages/tidy-tabs/lib/tidy-tabs.coffee:69:15)
  at Object.<anonymous> (/home/agordon/.atom/packages/tidy-tabs/lib/tidy-tabs.coffee:87:39)
  at Object.module.exports.TidyTabs.getItemsToClose (/home/agordon/.atom/packages/tidy-tabs/lib/tidy-tabs.coffee:100:10)
  at Object.module.exports.TidyTabs.tidy (/home/agordon/.atom/packages/tidy-tabs/lib/tidy-tabs.coffee:48:5)
  at /home/agordon/.atom/packages/tidy-tabs/lib/tidy-tabs.coffee:40:18
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:25.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:07.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:07.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:02.0 core:copy (atom-text-editor.editor.is-focused)
     -0:43.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:40.3.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:38.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:copy (atom-text-editor.editor.is-focused)
  4x -0:11.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "js-autoimport"
    ]
  },
  "tidy-tabs": {
    "runOnSave": true,
    "accessedThreshold": 3,
    "minimumTabs": 5
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.12
custom-title, v1.0.1
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
emmet, v2.3.12
language-babel, v0.14.0
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
linter, v1.5.1
linter-jshint, v1.2.0
linter-jsonlint, v1.0.1
linter-scss-lint, v2.0.0
pigments, v0.15.0
react, v0.12.9
settings-view, v0.218.0
simple-drag-drop-text, v0.3.0
tidy-tabs, v0.2.0

# Dev
No dev packages
```

**Comment by bradleyboy** [comment]
Should be resolved in 0.3.0. Let me know if you still have problems.
